models/Tasks.php
<?php

namespace app\models;

use app\base\AppActiveQuery;
use Yii;
use yii\behaviors\BlameableBehavior;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\web\ForbiddenHttpException;

/**
 * This is the model class for table "tasks".
 *
 * @property int $id
 * @property string $data
 * @property string $time
 * @property int $status
 * @property string $text
 * @property string $date_cr
 * @property string $date_up
 * @property int $manager
 * @property int $client
 * @property int $company_id Компания, к которой принадлжит запись
 *
 * @property Clients $client0
 * @property TaskStatuses $status0
 */
class Tasks extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $search_status;
    public static function tableName()
    {
        return 'tasks';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::class,
                'createdByAttribute' => 'company_id',
                'updatedByAttribute' => null,
                'value' => function($event) {
                    return Yii::$app->user->identity->company_id;
                },
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function find()
    {
        if(Yii::$app->user->isGuest == false){
            $companyId = Yii::$app->user->identity->getCompany();
        } else {
            $companyId = null;
        }

        return new AppActiveQuery(get_called_class(), [
            'companyId' => $companyId,
        ]);
    }

    /**
     * @inheritdoc
     */
    public static function findOne($condition)
    {
        $model = parent::findOne($condition);
        if(Yii::$app->user->isGuest == false) {
            if(Yii::$app->user->identity->isSuperAdmin() === false)
            {
                $companyId = Yii::$app->user->identity->getCompany();
                if($model->company_id != $companyId){
                    throw new ForbiddenHttpException('Доступ запрещен');
                }
            }
        }
        return $model;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['data', 'time', 'date_cr', 'date_up', 'notification_time'], 'safe'],
            [['status', 'manager', 'client', 'notification_status', 'tasks_type_id'], 'integer'],
            [['text', 'result_text'], 'string'],
            [['client'], 'exist', 'skipOnError' => true, 'targetClass' => Clients::className(), 'targetAttribute' => ['client' => 'id']],
            [['status'], 'exist', 'skipOnError' => true, 'targetClass' => TaskStatuses::className(), 'targetAttribute' => ['status' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Companies::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['tasks_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => TasksType::className(), 'targetAttribute' => ['tasks_type_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'data' => 'Дата',
            'time' => 'Время',
            'status' => 'Статус',
            'text' => 'Текст',
            'date_cr' => 'Дата создания',
            'date_up' => 'Дата изменения',
            'manager' => 'Менеджер',
            'client' => 'Клиент',
            'notification_time' => 'Отправить уведомление',
            'notification_status' => 'Статус уведомлении',
            'result_text' => 'Результат звонка',
            'tasks_type_id' => 'Тип задачи',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {
            $this->date_cr = date('Y-m-d H:i:s');
            $this->notification_status = null;
        }
        $this->date_up = date('Y-m-d H:i:s');
        $this->client0->planned_date = $this->data;
        $this->client0->save();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient0()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus0()
    {
        return $this->hasOne(TaskStatuses::className(), ['id' => 'status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManager0()
    {
        return $this->hasOne(Users::className(), ['id' => 'manager']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasksType()
    {
        return $this->hasOne(TasksType::className(), ['id' => 'tasks_type_id']);
    }

    /**
     * @return array
     */
    public function getManager()
    {
        $user = Yii::$app->user->identity;
        $companyId = $user->getCompany();

        if($companyId != null) {
            $managers = Users::find()->where(['type' => 2])->andWhere(['or', ['company_id' => $companyId], ['id' => $companyId]])->all();
        } else {
            $managers = Users::find()->where(['type' => 2])->all();
        }
        return ArrayHelper::map($managers, 'id', 'fio');
    }

    /**
     * @return array
     */
    public function getStatuses()
    {
        $customer_statuses = TaskStatuses::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all();
        return ArrayHelper::map($customer_statuses, 'id', 'name');
    }

    /**
     * @return array
     */
    public function getClients()
    {
        $client = Clients::find()->where(['company_id' => Yii::$app->user->identity->company_id])->orderBy('id DESC')->all();
        return ArrayHelper::map($client, 'id', 'fio');
    }

    public function getTypes()
    {
        $types = TasksType::find()->where(['company_id' => Yii::$app->user->identity->company_id])->all();
        return ArrayHelper::map($types, 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Companies::className(), ['id' => 'company_id']);
    }
}

controllers/TasksController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tasks;
use app\models\TasksSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Users;
use app\models\Companies;

/**
 * TasksController implements the CRUD actions for Tasks model.
 */
class TasksController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'companies' => [
                'class' => \app\filters\CompaniesFilter::class,
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tasks models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new TasksSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,Yii::$app->request->post());

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'post' => Yii::$app->request->post(),
        ]);
    }


    /**
     * Displays a single Tasks model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Задачи #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    public function actionViewFromDashboard($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Задачи #".$id,
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Изменить',['update-from-dashboard','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Tasks model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Tasks();  
        if(Yii::$app->user->identity->type == 2) $model->manager = Yii::$app->user->identity->id;
        $company = Companies::findOne(Yii::$app->user->identity->company_id);
        if($company == null)$time_zone = 0;
        else $time_zone = $company->time_zone;
        $now = date('d.m.Y H:i', strtotime( $time_zone . ' hour'));
        $now_time = date('H:i', strtotime( $time_zone . ' hour'));

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
              $model->time = $now_time;
              $model->notification_time = $now_time;
                return [
                    'title'=> "Создать | Сегодня " .  $now ,
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создать | Сегодня " . $now ,
                    'content'=>'<span class="text-success">Создание новой задачи успешно завершена</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать ещё',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{
              $model->time = $now_time;
              $model->notification_time = $now_time;
                return [
                    'title'=> "Создать | Сегодня " .  $now ,
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Уведомляет всех пользователей о срочных задачах
     * По умолчанию срочная задачей, является та задача,
     * которая начнется через 5 минут (300 милисекунд)
     * @return mixed
     */
    public function actionUrgentTasksNotify($reduceTime = 300)
    {
        $user = Yii::$app->user->identity;
        $users = Users::find()->where(['!=', 'id', $user->id])->hasToken()->all();
        $tasks = Tasks::find()->where(['data' => date('Y-m-d')])->all();

        foreach($tasks as $task)
        {
            $currentDateTime = strtotime(date('Y-m-d H:i:s'));
            $taskDateTime = strtotime($task->data.' '.$task->time);
            $timeDiff = $taskDateTime - $currentDateTime;

            if(($timeDiff < $reduceTime) && ($taskDateTime > $currentDateTime))
            {
                $YOUR_API_KEY = 'AAAAgRr2kLc:APA91bEzgweVGyzAtG7lRtQhAhiTc2sVMSCXcxjBlH7D5X4FR6OzS_0AejAb-AerriEl1xPkw5SIzzl5fTmgEtc3jRxbRG1OSoWXfz1T-GIKU3KYugpI4uQww4DSmEpJth7N0bE3rPL1'; // Server key
                $url = 'https://fcm.googleapis.com/fcm/send';

                foreach($users as $user)
                {
                  $YOUR_TOKEN_ID = $user->fcm_token;

                  $reduce = $timeDiff > 60 ? round($timeDiff/60, 0).' мин.' : $timeDiff.' сек.';

                  $request_body = [
                      'to' => $YOUR_TOKEN_ID,
                      'notification' => [
                          'title' => 'Задача начнется через '.$reduce,
                          'body' => $task->text,
                          'icon' => 'https://eralash.ru.rsz.io/sites/all/themes/eralash_v5/logo.png?width=192&height=192',
                          'click_action' => 'http://eralash.ru/',
                      ],
                  ];
                  $fields = json_encode($request_body);

                  $request_headers = [
                      'Content-Type: application/json',
                      'Authorization: key=' . $YOUR_API_KEY,
                  ];

                  $ch = curl_init();
                  curl_setopt($ch, CURLOPT_URL, $url);
                  curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
                  curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
                  curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
                  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
                  $response = curl_exec($ch);
                  curl_close($ch);
                }
            }
        }

        Yii::$app->session->setFlash('success', 'Уведомления успешно отправлены');

        return $this->redirect(['index']);
    }

    public function actionAdd($id)
    {
        $request = Yii::$app->request;
        $model = new Tasks();  
        if(Yii::$app->user->identity->type == 2) $model->manager = Yii::$app->user->identity->id;
         $model->client = $id;

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#tasks-pjax',
                    'title'=> "Создать",
                    'size' => 'normal',
                    'content'=>'<span class="text-success">Создание новой задачи успешно завершена</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).

views/tasks/_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\TaskStatuses;
use app\models\Clients;
use app\models\Users;

$company_id = Yii::$app->user->identity->company_id;

return [
    //[
        //'class' => 'kartik\grid\CheckboxColumn',
        //'width' => '20px',
    //],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'client',
        'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
        'filter' => ArrayHelper::map(Clients::find()->where(['company_id' => $company_id ])->orderBy('id DESC')->all(), 'id', 'fio'),
        'content' => function ($data) {
           if($data->client0->client == 1) return $data->client0->fio .' <a data-pjax=0 role="modal-remote" class="glyphicon glyphicon-eye-open" href="'.Url::toRoute(['clients/view-ajax-client', 'id' => $data->client]).'"></a>';
           else return $data->client0->fio .' <a data-pjax=0 role="modal-remote" class="glyphicon glyphicon-eye-open" href="'.Url::toRoute(['clients/view-ajax-lid', 'id' => $data->client]).'"></a>';
       },
    ],
    [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'manager',
         'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
         'filter' => ArrayHelper::map(Users::find()->where(['company_id' => $company_id ])->all(), 'id', 'fio'),
         'content' => function ($data) {
           return $data->manager0->fio;
       },
     ],
    [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'status',
         'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
         'filter' => ArrayHelper::map(TaskStatuses::find()->where(['company_id' => $company_id ])->all(), 'id', 'name'),
         'content' => function ($data) {
           return $data->status0->name;
       },
     ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'tasks_type_id',
         'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
         //'filter' => ArrayHelper::map(TaskStatuses::find()->where(['company_id' => $company_id ])->all(), 'id', 'name'),
         'content' => function ($data) {
           return $data->tasksType->name;
       },
     ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'time',
        'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'data',
        'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'color:black;background-color:'.$model->status0->color ];
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'text',
        'format' => 'raw',
        'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'width:30%; white-space: normal;color:black;background-color:'.$model->status0->color ];
        },
        //'contentOptions' => ['style' => 'width:30%; white-space: normal;'],
        'content' => function ($data) {
            return substr($data->text, 0, 300);
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'result_text',
        'format' => 'raw',
        'contentOptions' => function ($model, $key, $index, $column) {
            return ['style' => 'width:30%; white-space: normal;color:black;background-color:'.$model->status0->color ];
        },
        //'contentOptions' => ['style' => 'width:30%; white-space: normal;'],
        'content' => function ($data) {
            return substr($data->result_text, 0, 300);
        },
    ],
    //[
        //'class'=>'\kartik\grid\DataColumn',
        //'attribute'=>'date_cr',
    //],
    // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'date_up',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'template' => '{update}{delete}',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Вы уверены?',
                          'data-confirm-message'=>'Вы действительно хотите удалить этот элемент'], 
    ],

];   

views/tasks/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\time\TimePicker;
use dosamigos\datepicker\DatePicker;
/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tasks-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
             <?= $form->field($model, 'client')->dropDownList($model->getClients(), ['prompt' => 'Выберите клиента']) ?>
        </div>
        <div class="col-md-4">
             <?= $form->field($model, 'manager')->dropDownList(
                $model->getManager(), 
                [
                    'prompt' => 'Выберите менежера',
                    'disabled'=> Yii::$app->user->identity->type == 2 ? true : false,
                ]) ?>
        </div>
        <div class="col-md-4">
             <?= $form->field($model, 'status')->dropDownList($model->getStatuses(), ['prompt' => 'Выберите статуса']) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
             <?= $form->field($model, 'tasks_type_id')->dropDownList($model->getTypes(), ['prompt' => 'Выберите типа']) ?>
        </div>
        <div class="col-md-3">
             <?= $form->field($model, 'data')->widget(
                DatePicker::className(), [
                    'inline' => false,
                    'language' => 'ru',
                    'clientOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd'
                    ]
                ])
             ?>
        </div>
        <div class="col-md-3">  
            <?= $form->field($model, 'time')->widget(TimePicker::classname(), [
                'pluginOptions' => [
                    'showSeconds' => false,
                    'showMeridian' => false,
                    'minuteStep' => 1,
                    'secondStep' => 5,
                ]]); ?>
        </div>
        <div class="col-md-3">  
            <?= $form->field($model, 'notification_time')->widget(TimePicker::classname(), [
                'pluginOptions' => [
                    'showSeconds' => false,
                    'showMeridian' => false,
                    'minuteStep' => 1,
                    'secondStep' => 5,
                ]]); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'text')->widget(mihaildev\ckeditor\CKEditor::className(),[
                    'editorOptions' => [
                        'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                        'inline' => false, //по умолчанию false
                        'height' => '150px',
                    ],
                ]);
            ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'result_text')->widget(mihaildev\ckeditor\CKEditor::className(),[
                    'editorOptions' => [
                        'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                        'inline' => false, //по умолчанию false
                        'height' => '150px',
                    ],
                ]);
            ?>
        </div>
  
        <div style="display: none;">
             <?= $form->field($model, 'date_cr')->textInput() ?>
             <?= $form->field($model, 'date_up')->textInput() ?>
        </div>
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
    </div>
</div>

views/tasks/add.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

?>
<div class="tasks-create">
    <?= $this->render('add_form', [
        'model' => $model,
    ]) ?>
</div>

views/tasks/change.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
?>
<div class="tasks-update">

    <?= $this->render('add_form', [
        'model' => $model,
    ]) ?>

</div>

views/tasks/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Tasks */

?>
<div class="tasks-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/tasks/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TasksSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Задачи';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<!-- 
    
        <div class="panel panel-inverse" data-sortable-id="index-8">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Поиск</h4>
            </div>
            <div class="panel-body">
                
            </div>
        </div>
<br>
 --><div class="panel panel-inverse users-index">
    <div class="panel-heading">
<!--        <div class="panel-heading-btn">-->
<!--        </div>-->
        <h4 class="panel-title">Задачи</h4>
    </div>
    <div class="panel-body">
        <?php echo $this->render('_search', ['model' => $searchModel, 'post' => $post]); ?>
                <!-- <p style="margin-left: 41px;">
                    <a class="btn btn-warning" href="<?php // Url::toRoute(['tasks/urgent-tasks-notify'])?>">Сделать рассылку уведомлений срочных задач</a>
                </p> -->
        <div id="ajaxCrudDatatable">
            <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            //'filterModel' => $searchModel,
            'pjax'=>true,
            'responsiveWrap' => false,
            'columns' => require(__DIR__.'/_columns.php'),
            'panelBeforeTemplate' =>    Html::a('Добавить <i class="fa fa-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Добавить задач', 'style' => 'margin-left:30px;', 'class'=>'btn btn-success']).'&nbsp;'.
                Html::a('<i class="fa fa-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-white', 'title'=>'Обновить']),
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
            'headingOptions' => ['style' => 'display: none;'],
            'after'=>'',
            ]
            ])?>
        </div>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/tasks/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tasks */
?>
<div class="tasks-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>